apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: appjs
spec:
  serviceName: appjs
  replicas: 2
  template:
    metadata:
      labels:
        app: appjs
    spec:
      containers:
      - name: appjs
        image: jenoovchi/appjs-pet
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /var/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 1Mi
      accessModes:
      - ReadWriteOnce
