apiVersion: v1
kind: ReplicationController
metadata:
  name: appjs
spec:
  replicas: 3
  selector:
    app: appjs
  template:
    metadata:
      labels:
        app: appjs
    spec:
      containers:
      - image: jenoovchi/appjs
        name: appjs
        ports:
        - containerPort: 8080
