apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: appjs
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: appjs
      labels:
        app: appjs
    spec:
      containers:
      - image: jenoovchi/appjs:v3
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
