apiVersion: v1
kind: Service
metadata:
  name: appjs-headless-all
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: appjs
