apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appjs-nginx-hosts
spec:
  rules:
  - host: appjs-new.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: appjs-nodeport
          servicePort: 80
  - host: nginx-new.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-nodeport
          servicePort: 80
