apiVersion: v1
kind: Service
metadata:
  name: appjs-loadbalancer-local
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: appjs
