apiVersion: v1
kind: Pod
metadata:
  name: tomcat-mysql-svc-v2
spec:
  containers:
  - image: aallam/tomcat-mysql
    name: main
    env:
    - name: MYSQL_PASSWORD
      value: root
    ports:
    - name: tomcat
      containerPort: 8080
    - name: mysql
      containerPort: 3306
