apiVersion: v1
kind: Service
metadata:
  name: tomcat-mysql-svc
spec:
  ports:
  - name: tomcat
    port: 80
    targetPort: 8080
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: tomcat-mysql
