apiVersion: v1
kind: Service
metadata:
  name: tomcat-mysql-svc-by-name
spec:
  ports:
  - name: tomcat
    port: 80
    targetPort: tomcat
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: tomcat-mysql-svc-v2
