apiVersion: v1
kind: Pod
metadata:
  name: mongodb-aws
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    nfs:
      server: 1.2.3.4
      path: /some/path
